# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72e3e6f1670efbd11f7da27f537a5874a5a17a477adbf92932d4be0f22c9ab1fa3de350609b5a33b101e464bc22bfc612aee2a68ab4886306f893ad9d98eee3c

test:
  secret_key_base: 9635778e1eeec1c2a90011f3f28985772f2a4211adff6a4244d3e235c5bfb85c053bc50b38c64b8a4abf728266ef17ae9259972d825fdb537214ba813ce329da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
